# Generated by Django 5.1.3 on 2024-11-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('is_published', models.BooleanField()),
                ('time_create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
